### ISSUE TITLE
Microsoft Translator bookmarklets redundant?

### ISSUE THREAD

**Issue by grahamperrin** [riegelstamm/msxlatorbkmklet#1]
Hi

Re: https://github.com/riegelstamm/msxlatorbkmklet/commit/68661c76759cedce232bd5d5bcb9ff9e851f936c#diff-04c6e90faac2675aa89e2176d2eec7d8R4

`javascript:void(window.open('http://www.microsofttranslator.com/bv.aspx?from=&to=en&a='+location.href));`

<http://www.microsofttranslator.com/> now redirects to <https://www.bing.com/translator/>

Use of the bookmarklet seems to produce results at `www.translatetheweb.com` e.g. from https://www.s3blog.org/s3gt.html to https://www.translatetheweb.com/?from=&to=en&a=https://www.s3blog.org/s3gt.html with no **target language dropdown**. 

From [The Translator Web Widget will be retired soon - Microsoft Translator Blog](https://www.microsoft.com/en-us/translator/blog/2019/06/27/the-translator-web-widget-will-be-retired-soon/) (2019-06-27): 

> The Translator Web Widget will be retired on July 31, 2019. Beginning July 31st, the widget will no longer translate your webpages.

Does this mean that the bookmarklet is simply redundant (not fixable)? 

### Background

Re: https://www.microsoft.com/en-us/translator/apps/#lbl-5e00ba52353c4 I see that there's a plug-in for Microsoft Edge but that's no good on unsupported platforms. 

I use a variety of browsers, primarily home-built Waterfox Classic, on FreeBSD-CURRENT. For now it remains possible to perform in-page translation with carefully selected (or converted) extensions that make free use of a Google widget however re: https://redd.it/eekvsc there may be an end to this freedom.

**Comment by riegelstamm** [comment]
Hi Graham, thanks for letting me know the bookmarklet wasn't working. Microsoft changed the URL again. As you noted, they are now using translatetheweb.com. I fixed the bookmarklet so it works again, at least for me. Please let me know if it still doesn't work for you.

Cheers!

**Comment by grahamperrin** [comment]
Thanks! 

I didn't realise that `www.translatetheweb.com` is Microsoft-related; 

> … no target language dropdown.

– more specifically, I had this: 

![image](https://user-images.githubusercontent.com/192271/71366887-348c7400-259b-11ea-9c7d-e58967d04914.png)

My bad. uBlock Origin, which I rarely use, was active. After disabling eight built-in filters and reloading the page, the toolbar appeared for a split-second, disappeared before presenting translated content: 

![image](https://user-images.githubusercontent.com/192271/71367073-d01de480-259b-11ea-8df8-ed07e7ae2a78.png)

No better after disabling uBlock Origin for the site. I'll identify the offending preference (or extension) then add a comment and hide/resolve this one.

**Comment by riegelstamm** [comment]
I use the Brave browser, and here's what the page looks like after translating it:
![image](https://user-images.githubusercontent.com/10802064/71368314-35a6ac80-256d-11ea-864a-f1b65b93fd37.png)

**Comment by grahamperrin** [comment]
I used Extension Conflict Troubleshooter with Waterfox Classic 2019.12 to identify the troublesome extension, then reaffirmed the trouble with Firefox 71.0. 

[WebTranslate](https://addons.mozilla.org/addon/webtranslate/) 2.0.4 disabled: 

![image](https://user-images.githubusercontent.com/192271/71391423-f4a9a900-25fb-11ea-8975-62bb88d351aa.png)

Enabled: 

![image](https://user-images.githubusercontent.com/192271/71391534-7994c280-25fc-11ea-9839-7f083c2d6926.png)

I'll send an e-mail to the developer.
